[tool.poetry]
name = "card-knockout-game"
version = "0.1.0"
description = ""
authors = ["Andres Londoño <anfelipeloal@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
game = "src.card_knockout_game.main:game"